/**
 * IFC Functional Parts Catalog
 * Based on buildingSMART validation framework
 *
 * Functional parts are used to categorize normative IFC validation rules.
 * Each rule in the Gherkin rules framework has a code like "ALB001", "PJS007", "GEM042"
 * where the 3-letter prefix represents the functional part.
 *
 * References:
 * - Functional Parts: https://github.com/buildingSMART/validate/blob/docs/gh-pages/docs/dev/functional_parts.md
 * - Gherkin Rules: https://buildingsmart.github.io/ifc-gherkin-rules/branches/main/index.html
 */

export interface FunctionalPart {
  tag: string;
  name: string;
  description: string;
  category: 'core' | 'geometry' | 'placement' | 'positioning' | 'organization' | 'properties' | 'presentation' | 'connectivity' | 'management';
}

/**
 * Complete catalog of IFC functional parts
 */
export const FUNCTIONAL_PARTS_CATALOG: Record<string, FunctionalPart> = {
  // Core Elements
  PJS: {
    tag: 'PJS',
    name: 'Project definition',
    description: 'Overall context and directory of objects within the model, including default units and geometric representation context',
    category: 'core',
  },
  GRF: {
    tag: 'GRF',
    name: 'Georeferencing',
    description: 'Geographic location and orientation of the model relative to a reference coordinate system',
    category: 'core',
  },
  BLT: {
    tag: 'BLT',
    name: 'Built elements (kickable)',
    description: 'Building and infrastructure elements: walls, floors, roofs, stairs, doors, windows, columns, etc.',
    category: 'core',
  },
  ASM: {
    tag: 'ASM',
    name: 'Assemblies (kickable)',
    description: 'Elements composed of or constructed by other elements',
    category: 'core',
  },
  SPA: {
    tag: 'SPA',
    name: 'Spaces (non-kickable)',
    description: 'Spaces such as rooms, hallways, clearance zones, and circulation areas',
    category: 'core',
  },
  VRT: {
    tag: 'VRT',
    name: 'Virtual elements (non-kickable)',
    description: 'Imaginary, placeholder, or provisional areas, volumes, and boundaries',
    category: 'core',
  },

  // Geometry Representation
  GEM: {
    tag: 'GEM',
    name: 'Geometry representation',
    description: 'Various geometry types including parametric, mesh, and voxel-based representations',
    category: 'geometry',
  },
  AXG: {
    tag: 'AXG',
    name: 'Axis geometry',
    description: 'Geometry using axes with position and direction vectors',
    category: 'geometry',
  },
  ALS: {
    tag: 'ALS',
    name: 'Alignment geometry',
    description: 'Geometry using segments defining a linear path in 3D space',
    category: 'geometry',
  },
  PBG: {
    tag: 'PBG',
    name: 'Point-based geometry',
    description: 'Geometry using collection of individual points in 3D space',
    category: 'geometry',
  },
  TAS: {
    tag: 'TAS',
    name: 'Tessellated (meshes)',
    description: 'Geometry using interconnected vertices, edges, and faces',
    category: 'geometry',
  },
  BRP: {
    tag: 'BRP',
    name: 'Boundary Representation (BREP)',
    description: 'Geometry using connected surfaces and edges',
    category: 'geometry',
  },
  CSG: {
    tag: 'CSG',
    name: 'Constructive Solid Geometry',
    description: 'Complex geometry created by Boolean operations',
    category: 'geometry',
  },
  SWE: {
    tag: 'SWE',
    name: 'Sweeps (extrusions, lofts, blends)',
    description: '3D shapes generated by moving 2D profiles along paths',
    category: 'geometry',
  },
  TFM: {
    tag: 'TFM',
    name: 'Transformations',
    description: 'Spatial transformations: rotations, translations, scaling',
    category: 'geometry',
  },
  BBX: {
    tag: 'BBX',
    name: 'Bounding box',
    description: 'Orthogonal box defining spatial extent of geometry',
    category: 'geometry',
  },
  MPD: {
    tag: 'MPD',
    name: 'Mapped geometry',
    description: 'Reusable geometry representations with mapping',
    category: 'geometry',
  },
  RCO: {
    tag: 'RCO',
    name: 'Relational constructs',
    description: 'Connection geometry, space boundaries, interference geometries',
    category: 'geometry',
  },
  CPD: {
    tag: 'CPD',
    name: 'Clipped representations',
    description: 'Visualizations with parts clipped or cut away',
    category: 'geometry',
  },

  // Object Placement
  OJP: {
    tag: 'OJP',
    name: 'Object placement',
    description: 'Location, orientation, and scale of built elements and systems',
    category: 'placement',
  },
  LOP: {
    tag: 'LOP',
    name: 'Local placement',
    description: 'Placement relative to another product or absolute placement',
    category: 'placement',
  },
  LIP: {
    tag: 'LIP',
    name: 'Linear placement',
    description: 'Placement relative to a curve',
    category: 'placement',
  },
  GDP: {
    tag: 'GDP',
    name: 'Grid placement',
    description: 'Placement relative to a design grid',
    category: 'placement',
  },

  // Positioning Elements
  POS: {
    tag: 'POS',
    name: 'Positioning elements',
    description: 'Virtual objects used to position other elements relatively',
    category: 'positioning',
  },
  GRD: {
    tag: 'GRD',
    name: 'Grid',
    description: 'Design grid for object placement reference',
    category: 'positioning',
  },
  ALA: {
    tag: 'ALA',
    name: 'Alignment',
    description: 'Alignment curve and components for object placement',
    category: 'positioning',
  },
  ALB: {
    tag: 'ALB',
    name: 'Alignment',
    description: 'Alignment curve and components for object placement',
    category: 'positioning',
  },
  RFT: {
    tag: 'RFT',
    name: 'Referent',
    description: 'Referent for object placement reference',
    category: 'positioning',
  },

  // Organization & Structure
  OJT: {
    tag: 'OJT',
    name: 'Objects typing',
    description: 'Element type definitions allowing reusability of information',
    category: 'organization',
  },
  GRP: {
    tag: 'GRP',
    name: 'Groups (non-kickable)',
    description: 'Functional or logical grouping of objects (e.g., HVAC systems)',
    category: 'organization',
  },
  SPS: {
    tag: 'SPS',
    name: 'Spatial breakdown',
    description: 'Hierarchical spatial relationships: site→building→storey→room',
    category: 'organization',
  },

  // Properties & Data
  MAT: {
    tag: 'MAT',
    name: 'Materials',
    description: 'Material definitions assigned to elements',
    category: 'properties',
  },
  PSE: {
    tag: 'PSE',
    name: 'Properties for objects',
    description: 'Element and system properties such as performance characteristics',
    category: 'properties',
  },
  QTY: {
    tag: 'QTY',
    name: 'Quantities for objects',
    description: 'Element quantities: dimensions, volume, area, weight',
    category: 'properties',
  },
  CLS: {
    tag: 'CLS',
    name: 'Classification reference',
    description: 'Element classification according to systems like UNIFORMAT or Omniclass',
    category: 'properties',
  },

  // Presentation
  ANN: {
    tag: 'ANN',
    name: 'Annotations',
    description: 'Labels, notes, and dimensions on elements and spaces',
    category: 'presentation',
  },
  LAY: {
    tag: 'LAY',
    name: 'Presentation layer',
    description: 'CAD layers for grouping and visibility control',
    category: 'presentation',
  },
  CTX: {
    tag: 'CTX',
    name: 'Presentation Colours and Textures',
    description: 'Color, texture and appearance information for objects',
    category: 'presentation',
  },

  // Connectivity & Analysis
  POR: {
    tag: 'POR',
    name: 'Port connectivity & nesting',
    description: 'Port definitions and relationships between ports',
    category: 'connectivity',
  },
  STR: {
    tag: 'STR',
    name: 'Structural items and actions',
    description: 'Structural members, connections, actions, and reactions',
    category: 'connectivity',
  },

  // Management
  CST: {
    tag: 'CST',
    name: 'Costing',
    description: 'Costing information assigned to objects',
    category: 'management',
  },
  SDL: {
    tag: 'SDL',
    name: 'Scheduling of activities',
    description: 'Scheduling information assigned to objects',
    category: 'management',
  },
  LIB: {
    tag: 'LIB',
    name: 'Library reference',
    description: 'Association with library entities or external databases',
    category: 'management',
  },
  DOC: {
    tag: 'DOC',
    name: 'Documentation reference',
    description: 'Documentation references associated with objects',
    category: 'management',
  },
  CTR: {
    tag: 'CTR',
    name: 'Constraints',
    description: 'Constraints on elements: dimensions, clearances',
    category: 'management',
  },
  VER: {
    tag: 'VER',
    name: 'Versioning / revision control',
    description: 'Change tracking and history maintenance',
    category: 'management',
  },
};

/**
 * Get functional part by TAG
 */
export function getFunctionalPart(tag: string): FunctionalPart | undefined {
  return FUNCTIONAL_PARTS_CATALOG[tag.toUpperCase()];
}

/**
 * Get functional parts by category
 */
export function getFunctionalPartsByCategory(category: FunctionalPart['category']): FunctionalPart[] {
  return Object.values(FUNCTIONAL_PARTS_CATALOG).filter(part => part.category === category);
}

/**
 * Mapping from validation error codes/types to functional part TAGs
 */
export const ERROR_TO_FUNCTIONAL_PART: Record<string, string> = {
  // Header Errors → Project Definition
  'HDR001': 'PJS',
  'HDR002': 'PJS',
  'HDR003': 'PJS',
  'HDR004': 'PJS',
  'HDR005': 'PJS',
  'HDR006': 'PJS',
  'HDR007': 'PJS',
  'HDR008': 'PJS',
  'HDR009': 'PJS',
  'HDR010': 'PJS',
  'HDR011': 'PJS',

  // Syntax Errors → Schema validation (general)
  'SYN001': 'PJS',
  'SYN002': 'PJS',
  'SYN003': 'PJS',
  'SYN004': 'PJS',
  'SYN005': 'PJS',

  // Entity/Type validation → Objects typing
  'VAL001': 'OJT',

  // Missing required properties → Properties
  'VAL002': 'PSE',
  'VAL002B': 'PSE',
  'VAL002C': 'VER', // OwnerHistory → Versioning

  // Data type errors → Properties
  'VAL003': 'PSE',

  // Reference errors → Organization
  'VAL004': 'GRP',
  'VAL005': 'GRP',

  // Cardinality errors → Properties
  'VAL006': 'PSE',

  // Broken/Circular references → Spatial breakdown
  'VAL007': 'SPS',
};

/**
 * Map validation type to functional part TAG
 */
export function mapValidationTypeToFunctionalPart(type: string, code?: string): string {
  // Try by error code first
  if (code && ERROR_TO_FUNCTIONAL_PART[code]) {
    return ERROR_TO_FUNCTIONAL_PART[code];
  }

  // Map by validation type
  const typeUpper = type.toUpperCase();

  // Syntax and file format
  if (typeUpper.includes('SYNTAX') || typeUpper.includes('FILE_FORMAT') || typeUpper.includes('INCOMPLETE')) {
    return 'PJS';
  }

  // Header
  if (typeUpper.includes('HEADER')) {
    return 'PJS';
  }

  // Properties and schema
  if (typeUpper.includes('PROPERTY') || typeUpper.includes('ATTRIBUTE')) {
    return 'PSE';
  }

  if (typeUpper.includes('MISSING_REQUIRED')) {
    return 'PSE';
  }

  if (typeUpper.includes('DATA_TYPE') || typeUpper.includes('CARDINALITY')) {
    return 'PSE';
  }

  // References and relationships
  if (typeUpper.includes('REFERENCE') || typeUpper.includes('CIRCULAR')) {
    return 'SPS';
  }

  // Geometry
  if (typeUpper.includes('GEOMETRY') || typeUpper.includes('SHAPE')) {
    return 'GEM';
  }

  // Materials
  if (typeUpper.includes('MATERIAL')) {
    return 'MAT';
  }

  // Quantities
  if (typeUpper.includes('QUANTITY')) {
    return 'QTY';
  }

  // Classification
  if (typeUpper.includes('CLASSIFICATION')) {
    return 'CLS';
  }

  // Spatial structure
  if (typeUpper.includes('SPATIAL') || typeUpper.includes('HIERARCHY')) {
    return 'SPS';
  }

  // Placement
  if (typeUpper.includes('PLACEMENT') || typeUpper.includes('LOCATION')) {
    return 'OJP';
  }

  // Entity types
  if (typeUpper.includes('ENTITY') || typeUpper.includes('TYPE')) {
    return 'OJT';
  }

  // Default: Project Definition
  return 'PJS';
}

/**
 * Map buildingSMART feature to functional part TAG
 * Handles both rule codes (e.g., "ALB001", "PJS007") and feature descriptions
 */
export function mapBuildingSmartFeatureToFunctionalPart(feature: string): string {
  const featureLower = feature.toLowerCase();

  // Check if it's a rule code format (e.g., "ALB001", "PJS007", "GEM042")
  // Rule codes are 3-letter prefix + 3 digits
  const ruleCodeMatch = feature.match(/^([A-Z]{3})\d{3}$/i);
  if (ruleCodeMatch) {
    const prefix = ruleCodeMatch[1].toUpperCase();
    // Validate it's a known functional part
    if (FUNCTIONAL_PARTS_CATALOG[prefix]) {
      return prefix;
    }
  }

  // Check if feature contains a rule code anywhere in it
  const embeddedRuleMatch = feature.match(/([A-Z]{3})\d{3}/i);
  if (embeddedRuleMatch) {
    const prefix = embeddedRuleMatch[1].toUpperCase();
    if (FUNCTIONAL_PARTS_CATALOG[prefix]) {
      return prefix;
    }
  }

  // Fallback to keyword-based mapping for features without rule codes

  // Project structure and file
  if (featureLower.includes('file') || featureLower.includes('header') || featureLower.includes('project')) {
    return 'PJS';
  }

  // Georeferencing
  if (featureLower.includes('georef') || featureLower.includes('coordinate') || featureLower.includes('crs')) {
    return 'GRF';
  }

  // Built elements
  if (featureLower.includes('wall') || featureLower.includes('slab') || featureLower.includes('beam') ||
      featureLower.includes('column') || featureLower.includes('door') || featureLower.includes('window') ||
      featureLower.includes('builtelement') || featureLower.includes('building element')) {
    return 'BLT';
  }

  // Spaces
  if (featureLower.includes('space') || featureLower.includes('room') || featureLower.includes('zone')) {
    return 'SPA';
  }

  // Geometry
  if (featureLower.includes('geometry') || featureLower.includes('shape') || featureLower.includes('representation')) {
    return 'GEM';
  }

  // Placement
  if (featureLower.includes('placement') || featureLower.includes('location') || featureLower.includes('position')) {
    return 'OJP';
  }

  // Grid
  if (featureLower.includes('grid')) {
    return 'GRD';
  }

  // Alignment
  if (featureLower.includes('alignment')) {
    return 'ALA';
  }

  // Object types
  if (featureLower.includes('type') || featureLower.includes('occurrence')) {
    return 'OJT';
  }

  // Groups and systems
  if (featureLower.includes('group') || featureLower.includes('system')) {
    return 'GRP';
  }

  // Spatial structure
  if (featureLower.includes('spatial') || featureLower.includes('storey') || featureLower.includes('building') ||
      featureLower.includes('site') || featureLower.includes('container')) {
    return 'SPS';
  }

  // Materials
  if (featureLower.includes('material')) {
    return 'MAT';
  }

  // Properties (most common)
  if (featureLower.includes('property') || featureLower.includes('attribute') || featureLower.includes('pset')) {
    return 'PSE';
  }

  // Quantities
  if (featureLower.includes('quantity') || featureLower.includes('qto')) {
    return 'QTY';
  }

  // Classification
  if (featureLower.includes('classification')) {
    return 'CLS';
  }

  // Annotations
  if (featureLower.includes('annotation') || featureLower.includes('dimension')) {
    return 'ANN';
  }

  // Layers
  if (featureLower.includes('layer')) {
    return 'LAY';
  }

  // Colors and textures
  if (featureLower.includes('color') || featureLower.includes('colour') || featureLower.includes('texture') ||
      featureLower.includes('style') || featureLower.includes('appearance')) {
    return 'CTX';
  }

  // Port connectivity
  if (featureLower.includes('port') || featureLower.includes('connect')) {
    return 'POR';
  }

  // Structural
  if (featureLower.includes('structural') || featureLower.includes('load') || featureLower.includes('action')) {
    return 'STR';
  }

  // Cost
  if (featureLower.includes('cost')) {
    return 'CST';
  }

  // Schedule
  if (featureLower.includes('schedule') || featureLower.includes('task')) {
    return 'SDL';
  }

  // Library
  if (featureLower.includes('library')) {
    return 'LIB';
  }

  // Documentation
  if (featureLower.includes('document')) {
    return 'DOC';
  }

  // Constraints
  if (featureLower.includes('constraint')) {
    return 'CTR';
  }

  // Versioning
  if (featureLower.includes('version') || featureLower.includes('revision') || featureLower.includes('history')) {
    return 'VER';
  }

  // Default: Project Definition
  return 'PJS';
}

/**
 * Get all categories with their parts
 */
export function getFunctionalPartsGroupedByCategory() {
  const grouped: Record<string, FunctionalPart[]> = {};

  Object.values(FUNCTIONAL_PARTS_CATALOG).forEach(part => {
    if (!grouped[part.category]) {
      grouped[part.category] = [];
    }
    grouped[part.category].push(part);
  });

  return grouped;
}
